
export const CONTRACT_ADDRESS = process.env.REACT_APP_PASSPORT_CONTRACT_ADDRESS;
export const ROLE_CONTRACT_ADDRESS = process.env.REACT_APP_RBAC_CONTRACT_ADDRESS;

export const PINATA_API_KEY = process.env.REACT_APP_PINATA_API_KEY;
export const PINATA_SECRET_API_KEY = process.env.REACT_APP_PINATA_SECRET_API_KEY;
